name: 🔥 Migrate database on merge

on:
  push:
    branches:
      - main

jobs:
  migration:
    name: 🔑 Migrate database
    runs-on: ubuntu-latest

    environment: Production
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        run: npm ci

      - name: Create database
        continue-on-error: true
        run: npm run db:create

      - name: Migrate database
        run: npm run db:migrate
